### ISSUE TITLE
Missing CORS headers?

### ISSUE THREAD

**Issue by winkler1** [danesparza/Dashboard#1]
Getting this on all the requests...

XMLHttpRequest cannot load http://service.cagedtornado.com:3030/forecast/42.3,-71.2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.

**Comment by danesparza** [comment]
Correct.  You'll need to setup your own Forecast service.  I have open sourced those as well (see the links at the bottom of the README)
